name: Build

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    runs-on: windows-latest
    name: Testing
    strategy:
      matrix:
        dotnet: [ 'netcoreapp3.1', 'net5.0' ]
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Run tests
        run: dotnet test --verbosity normal -f ${{ matrix.dotnet }}

  build:
    runs-on: windows-latest
    name: Building
    strategy:
      matrix: 
        dotnet: ['netcoreapp3.1', 'net5.0']
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Cleaning
        run: dotnet clean

      - name: Restore NuGet packages
        run: dotnet restore ExpressionEngine.sln

      - name: Build solution
        run: dotnet build -o ../build/${{ matrix.dotnet }} -c Release --no-restore -m:1 -f ${{ matrix.dotnet }}

      - name: Archive build to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            build/${{ matrix.dotnet }}/*
          retention-days: 5