name: "Create issues from todo"

on:
  push:
    branches:
      - 'dev'
      - 'feature/**'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v2.4"
        id: "todo"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_MARKER: "//"
          LABEL: "// TODO"